export interface EmojiEntry {
  char: string
  name: string
  keywords: string[]
}

export interface EmojiCategoryData {
  id: string
  label: string
  emojis: EmojiEntry[]
}

export const EMOJI_CATEGORIES: EmojiCategoryData[] = [
  {
    id: 'smileys',
    label: 'Smileys & People',
    emojis: [
      { char: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'grin'] },
      { char: '😃', name: 'grinning face with big eyes', keywords: ['smile', 'happy'] },
      { char: '😄', name: 'grinning face with smiling eyes', keywords: ['smile', 'happy', 'laugh'] },
      { char: '😁', name: 'beaming face', keywords: ['smile', 'happy', 'grin'] },
      { char: '😆', name: 'grinning squinting face', keywords: ['laugh', 'happy'] },
      { char: '😅', name: 'grinning face with sweat', keywords: ['laugh', 'nervous', 'sweat'] },
      { char: '🤣', name: 'rolling on the floor laughing', keywords: ['lol', 'laugh', 'rofl'] },
      { char: '😂', name: 'face with tears of joy', keywords: ['lol', 'laugh', 'cry'] },
      { char: '🙂', name: 'slightly smiling face', keywords: ['smile'] },
      { char: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm'] },
      { char: '😉', name: 'winking face', keywords: ['wink', 'flirt'] },
      { char: '😊', name: 'smiling face with smiling eyes', keywords: ['smile', 'happy', 'blush'] },
      { char: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
      { char: '🥰', name: 'smiling face with hearts', keywords: ['love', 'crush'] },
      { char: '😍', name: 'heart eyes', keywords: ['love', 'crush', 'adore'] },
      { char: '🤩', name: 'star-struck', keywords: ['wow', 'excited'] },
      { char: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love'] },
      { char: '😗', name: 'kissing face', keywords: ['kiss'] },
      { char: '😋', name: 'face savoring food', keywords: ['yum', 'tasty', 'delicious'] },
      { char: '😛', name: 'face with tongue', keywords: ['tongue', 'silly'] },
      { char: '😜', name: 'winking face with tongue', keywords: ['silly', 'joke'] },
      { char: '🤪', name: 'zany face', keywords: ['crazy', 'silly'] },
      { char: '😝', name: 'squinting face with tongue', keywords: ['silly', 'joke'] },
      { char: '🤑', name: 'money-mouth face', keywords: ['money', 'rich'] },
      { char: '🤗', name: 'hugging face', keywords: ['hug', 'embrace'] },
      { char: '🤭', name: 'face with hand over mouth', keywords: ['giggle', 'oops'] },
      { char: '🤫', name: 'shushing face', keywords: ['quiet', 'secret'] },
      { char: '🤔', name: 'thinking face', keywords: ['think', 'hmm', 'consider'] },
      { char: '🤐', name: 'zipper-mouth face', keywords: ['quiet', 'silence'] },
      { char: '🙄', name: 'face with rolling eyes', keywords: ['annoyed', 'eyeroll'] },
      { char: '😏', name: 'smirking face', keywords: ['smug', 'sly'] },
      { char: '😣', name: 'persevering face', keywords: ['struggle', 'annoyed'] },
      { char: '😥', name: 'sad but relieved face', keywords: ['sad', 'relief'] },
      { char: '😮', name: 'face with open mouth', keywords: ['wow', 'surprise'] },
      { char: '🤐', name: 'zipper mouth', keywords: ['secret'] },
      { char: '😯', name: 'hushed face', keywords: ['surprise', 'silent'] },
      { char: '😪', name: 'sleepy face', keywords: ['tired', 'sleep'] },
      { char: '😫', name: 'tired face', keywords: ['exhausted', 'tired'] },
      { char: '🥱', name: 'yawning face', keywords: ['tired', 'sleepy', 'bored'] },
      { char: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz'] },
      { char: '😌', name: 'relieved face', keywords: ['calm', 'relief'] },
      { char: '😛', name: 'tongue out', keywords: ['silly'] },
      { char: '😒', name: 'unamused face', keywords: ['annoyed', 'meh'] },
      { char: '😓', name: 'downcast face with sweat', keywords: ['stressed', 'sweat'] },
      { char: '😔', name: 'pensive face', keywords: ['sad', 'thoughtful'] },
      { char: '😕', name: 'confused face', keywords: ['confused', 'unsure'] },
      { char: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'] },
      { char: '😖', name: 'confounded face', keywords: ['frustrated'] },
      { char: '😞', name: 'disappointed face', keywords: ['sad', 'disappointed'] },
      { char: '😟', name: 'worried face', keywords: ['worried', 'concerned'] },
      { char: '😤', name: 'face with steam from nose', keywords: ['angry', 'proud'] },
      { char: '😢', name: 'crying face', keywords: ['sad', 'cry', 'tear'] },
      { char: '😭', name: 'loudly crying face', keywords: ['sad', 'cry', 'sob'] },
      { char: '😦', name: 'frowning face with open mouth', keywords: ['shock'] },
      { char: '😧', name: 'anguished face', keywords: ['shock', 'pain'] },
      { char: '😨', name: 'fearful face', keywords: ['scared', 'fear'] },
      { char: '😩', name: 'weary face', keywords: ['tired', 'stressed'] },
      { char: '🤯', name: 'exploding head', keywords: ['mind blown', 'shock'] },
      { char: '😬', name: 'grimacing face', keywords: ['awkward', 'nervous'] },
      { char: '😰', name: 'anxious face with sweat', keywords: ['nervous', 'anxious'] },
      { char: '😱', name: 'face screaming in fear', keywords: ['scream', 'shock'] },
      { char: '🥵', name: 'hot face', keywords: ['hot', 'heat'] },
      { char: '🥶', name: 'cold face', keywords: ['cold', 'freeze'] },
      { char: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush'] },
      { char: '🤪', name: 'zany', keywords: ['crazy'] },
      { char: '😵', name: 'dizzy face', keywords: ['dizzy', 'confused'] },
      { char: '🥴', name: 'woozy face', keywords: ['dizzy', 'drunk'] },
      { char: '😠', name: 'angry face', keywords: ['angry', 'mad'] },
      { char: '😡', name: 'pouting face', keywords: ['angry', 'rage'] },
      { char: '🤬', name: 'face with symbols on mouth', keywords: ['angry', 'swear'] },
      { char: '😷', name: 'face with medical mask', keywords: ['sick', 'mask'] },
      { char: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever'] },
      { char: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injured'] },
      { char: '🤢', name: 'nauseated face', keywords: ['sick', 'gross'] },
      { char: '🤮', name: 'face vomiting', keywords: ['sick', 'gross'] },
      { char: '🤧', name: 'sneezing face', keywords: ['sick', 'sneeze'] },
      { char: '😇', name: 'angel', keywords: ['innocent'] },
      { char: '🥳', name: 'partying face', keywords: ['party', 'celebrate'] },
      { char: '🥸', name: 'disguised face', keywords: ['disguise', 'incognito'] },
      { char: '😎', name: 'smiling face with sunglasses', keywords: ['cool'] },
      { char: '🤓', name: 'nerd face', keywords: ['nerd', 'geek'] },
      { char: '🧐', name: 'face with monocle', keywords: ['inspect', 'curious'] },
      { char: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'bye'] },
      { char: '👍', name: 'thumbs up', keywords: ['like', 'yes', 'approve'] },
      { char: '👎', name: 'thumbs down', keywords: ['dislike', 'no'] },
      { char: '👏', name: 'clapping hands', keywords: ['applause', 'clap', 'bravo'] },
      { char: '🙌', name: 'raising hands', keywords: ['celebrate', 'hooray'] },
      { char: '🙏', name: 'folded hands', keywords: ['please', 'pray', 'thanks'] },
      { char: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle'] },
      { char: '👌', name: 'OK hand', keywords: ['ok', 'perfect'] },
      { char: '✌️', name: 'victory hand', keywords: ['peace', 'victory'] },
      { char: '🤝', name: 'handshake', keywords: ['deal', 'agreement'] },
      { char: '❤️', name: 'red heart', keywords: ['love', 'heart'] },
      { char: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad'] },
    ],
  },
  {
    id: 'nature',
    label: 'Animals & Nature',
    emojis: [
      { char: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet'] },
      { char: '🐱', name: 'cat face', keywords: ['cat', 'kitten', 'pet'] },
      { char: '🐭', name: 'mouse face', keywords: ['mouse'] },
      { char: '🐹', name: 'hamster', keywords: ['hamster', 'pet'] },
      { char: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny'] },
      { char: '🦊', name: 'fox', keywords: ['fox'] },
      { char: '🐻', name: 'bear', keywords: ['bear'] },
      { char: '🐼', name: 'panda', keywords: ['panda'] },
      { char: '🐨', name: 'koala', keywords: ['koala'] },
      { char: '🐯', name: 'tiger face', keywords: ['tiger'] },
      { char: '🦁', name: 'lion', keywords: ['lion'] },
      { char: '🐮', name: 'cow face', keywords: ['cow'] },
      { char: '🐷', name: 'pig face', keywords: ['pig'] },
      { char: '🐸', name: 'frog', keywords: ['frog'] },
      { char: '🐵', name: 'monkey face', keywords: ['monkey'] },
      { char: '🐔', name: 'chicken', keywords: ['chicken'] },
      { char: '🐧', name: 'penguin', keywords: ['penguin'] },
      { char: '🐦', name: 'bird', keywords: ['bird'] },
      { char: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic'] },
      { char: '🐝', name: 'honeybee', keywords: ['bee', 'insect'] },
      { char: '🐢', name: 'turtle', keywords: ['turtle'] },
      { char: '🐍', name: 'snake', keywords: ['snake'] },
      { char: '🐳', name: 'spouting whale', keywords: ['whale', 'ocean'] },
      { char: '🐬', name: 'dolphin', keywords: ['dolphin', 'ocean'] },
      { char: '🐠', name: 'tropical fish', keywords: ['fish', 'ocean'] },
      { char: '🦋', name: 'butterfly', keywords: ['butterfly'] },
      { char: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring'] },
      { char: '🌹', name: 'rose', keywords: ['flower', 'rose'] },
      { char: '🌻', name: 'sunflower', keywords: ['flower', 'sun'] },
      { char: '🌵', name: 'cactus', keywords: ['plant', 'desert'] },
      { char: '🌲', name: 'evergreen tree', keywords: ['tree', 'forest'] },
      { char: '🍀', name: 'four leaf clover', keywords: ['luck', 'clover'] },
      { char: '🌈', name: 'rainbow', keywords: ['rainbow', 'colorful'] },
      { char: '☀️', name: 'sun', keywords: ['sun', 'sunny'] },
      { char: '⭐', name: 'star', keywords: ['star'] },
      { char: '🌙', name: 'crescent moon', keywords: ['moon', 'night'] },
      { char: '☁️', name: 'cloud', keywords: ['cloud', 'weather'] },
      { char: '⚡', name: 'high voltage', keywords: ['lightning', 'zap', 'energy'] },
      { char: '🔥', name: 'fire', keywords: ['fire', 'hot', 'lit'] },
      { char: '❄️', name: 'snowflake', keywords: ['snow', 'cold', 'winter'] },
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    emojis: [
      { char: '🍎', name: 'red apple', keywords: ['apple', 'fruit'] },
      { char: '🍊', name: 'tangerine', keywords: ['orange', 'fruit'] },
      { char: '🍋', name: 'lemon', keywords: ['lemon', 'fruit'] },
      { char: '🍌', name: 'banana', keywords: ['banana', 'fruit'] },
      { char: '🍉', name: 'watermelon', keywords: ['watermelon', 'fruit'] },
      { char: '🍇', name: 'grapes', keywords: ['grapes', 'fruit'] },
      { char: '🍓', name: 'strawberry', keywords: ['strawberry', 'fruit'] },
      { char: '🍑', name: 'peach', keywords: ['peach', 'fruit'] },
      { char: '🥝', name: 'kiwi fruit', keywords: ['kiwi', 'fruit'] },
      { char: '🍍', name: 'pineapple', keywords: ['pineapple', 'fruit'] },
      { char: '🥑', name: 'avocado', keywords: ['avocado'] },
      { char: '🍅', name: 'tomato', keywords: ['tomato'] },
      { char: '🌽', name: 'ear of corn', keywords: ['corn'] },
      { char: '🥕', name: 'carrot', keywords: ['carrot'] },
      { char: '🍕', name: 'pizza', keywords: ['pizza', 'food'] },
      { char: '🍔', name: 'hamburger', keywords: ['burger', 'food'] },
      { char: '🍟', name: 'french fries', keywords: ['fries', 'food'] },
      { char: '🌭', name: 'hot dog', keywords: ['hotdog', 'food'] },
      { char: '🥪', name: 'sandwich', keywords: ['sandwich', 'food'] },
      { char: '🌮', name: 'taco', keywords: ['taco', 'food'] },
      { char: '🍣', name: 'sushi', keywords: ['sushi', 'food'] },
      { char: '🍜', name: 'steaming bowl', keywords: ['noodles', 'ramen', 'food'] },
      { char: '🍝', name: 'spaghetti', keywords: ['pasta', 'food'] },
      { char: '🍦', name: 'soft ice cream', keywords: ['icecream', 'dessert'] },
      { char: '🍩', name: 'doughnut', keywords: ['donut', 'dessert'] },
      { char: '🍪', name: 'cookie', keywords: ['cookie', 'dessert'] },
      { char: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday'] },
      { char: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'] },
      { char: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'dessert'] },
      { char: '☕', name: 'hot beverage', keywords: ['coffee', 'tea'] },
      { char: '🍵', name: 'teacup without handle', keywords: ['tea'] },
      { char: '🍺', name: 'beer mug', keywords: ['beer', 'drink'] },
      { char: '🍷', name: 'wine glass', keywords: ['wine', 'drink'] },
      { char: '🥂', name: 'clinking glasses', keywords: ['cheers', 'toast', 'drink'] },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    emojis: [
      { char: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'sport'] },
      { char: '🏀', name: 'basketball', keywords: ['basketball', 'sport'] },
      { char: '🏈', name: 'american football', keywords: ['football', 'sport'] },
      { char: '⚾', name: 'baseball', keywords: ['baseball', 'sport'] },
      { char: '🎾', name: 'tennis', keywords: ['tennis', 'sport'] },
      { char: '🏐', name: 'volleyball', keywords: ['volleyball', 'sport'] },
      { char: '🏉', name: 'rugby football', keywords: ['rugby', 'sport'] },
      { char: '🎱', name: 'pool 8 ball', keywords: ['billiards', 'pool'] },
      { char: '🏓', name: 'ping pong', keywords: ['tabletennis', 'sport'] },
      { char: '🏸', name: 'badminton', keywords: ['badminton', 'sport'] },
      { char: '🥅', name: 'goal net', keywords: ['goal', 'sport'] },
      { char: '⛳', name: 'flag in hole', keywords: ['golf'] },
      { char: '🏹', name: 'bow and arrow', keywords: ['archery'] },
      { char: '🎣', name: 'fishing pole', keywords: ['fishing'] },
      { char: '🤿', name: 'diving mask', keywords: ['diving', 'snorkel'] },
      { char: '🥊', name: 'boxing glove', keywords: ['boxing'] },
      { char: '🥋', name: 'martial arts uniform', keywords: ['karate', 'judo'] },
      { char: '🎽', name: 'running shirt', keywords: ['running', 'race'] },
      { char: '🛹', name: 'skateboard', keywords: ['skateboard'] },
      { char: '🛼', name: 'roller skate', keywords: ['skating'] },
      { char: '🎿', name: 'skis', keywords: ['ski', 'snow'] },
      { char: '⛸️', name: 'ice skate', keywords: ['iceskating'] },
      { char: '🥌', name: 'curling stone', keywords: ['curling'] },
      { char: '🎯', name: 'direct hit', keywords: ['target', 'dart', 'goal'] },
      { char: '🎮', name: 'video game', keywords: ['gaming', 'controller'] },
      { char: '🎲', name: 'game die', keywords: ['dice', 'game'] },
      { char: '🧩', name: 'puzzle piece', keywords: ['puzzle'] },
      { char: '🎨', name: 'artist palette', keywords: ['art', 'paint'] },
      { char: '🎭', name: 'performing arts', keywords: ['theater', 'drama'] },
      { char: '🎪', name: 'circus tent', keywords: ['circus'] },
      { char: '🎬', name: 'clapper board', keywords: ['movie', 'film'] },
      { char: '🎤', name: 'microphone', keywords: ['sing', 'music'] },
      { char: '🎧', name: 'headphone', keywords: ['music', 'audio'] },
      { char: '🎼', name: 'musical score', keywords: ['music'] },
      { char: '🎹', name: 'musical keyboard', keywords: ['piano', 'music'] },
      { char: '🥁', name: 'drum', keywords: ['drum', 'music'] },
      { char: '🎸', name: 'guitar', keywords: ['guitar', 'music'] },
      { char: '🏆', name: 'trophy', keywords: ['trophy', 'award', 'win'] },
      { char: '🥇', name: 'gold medal', keywords: ['medal', 'first', 'win'] },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    emojis: [
      { char: '🚗', name: 'car', keywords: ['car', 'drive'] },
      { char: '🚕', name: 'taxi', keywords: ['taxi', 'cab'] },
      { char: '🚌', name: 'bus', keywords: ['bus'] },
      { char: '🚓', name: 'police car', keywords: ['police'] },
      { char: '🚑', name: 'ambulance', keywords: ['ambulance'] },
      { char: '🚒', name: 'fire engine', keywords: ['firetruck'] },
      { char: '🚲', name: 'bicycle', keywords: ['bike', 'cycle'] },
      { char: '🛵', name: 'motor scooter', keywords: ['scooter'] },
      { char: '✈️', name: 'airplane', keywords: ['flight', 'travel', 'plane'] },
      { char: '🚀', name: 'rocket', keywords: ['rocket', 'launch', 'space'] },
      { char: '🚁', name: 'helicopter', keywords: ['helicopter'] },
      { char: '⛵', name: 'sailboat', keywords: ['boat', 'sailing'] },
      { char: '🚢', name: 'ship', keywords: ['ship', 'cruise'] },
      { char: '🚂', name: 'locomotive', keywords: ['train'] },
      { char: '🚆', name: 'train', keywords: ['train', 'rail'] },
      { char: '🚊', name: 'tram', keywords: ['tram'] },
      { char: '🗺️', name: 'world map', keywords: ['map', 'travel'] },
      { char: '🗽', name: 'statue of liberty', keywords: ['newyork', 'landmark'] },
      { char: '🗼', name: 'tokyo tower', keywords: ['tower', 'landmark'] },
      { char: '🏰', name: 'castle', keywords: ['castle'] },
      { char: '🏯', name: 'japanese castle', keywords: ['castle', 'japan'] },
      { char: '🏟️', name: 'stadium', keywords: ['stadium'] },
      { char: '🎡', name: 'ferris wheel', keywords: ['carnival'] },
      { char: '🎢', name: 'roller coaster', keywords: ['coaster'] },
      { char: '⛱️', name: 'umbrella on ground', keywords: ['beach'] },
      { char: '🏖️', name: 'beach with umbrella', keywords: ['beach', 'vacation'] },
      { char: '🏝️', name: 'desert island', keywords: ['island', 'beach'] },
      { char: '⛰️', name: 'mountain', keywords: ['mountain'] },
      { char: '🏔️', name: 'snow-capped mountain', keywords: ['mountain', 'snow'] },
      { char: '🌋', name: 'volcano', keywords: ['volcano'] },
      { char: '🏕️', name: 'camping', keywords: ['camp', 'tent'] },
      { char: '🏙️', name: 'cityscape', keywords: ['city'] },
      { char: '🌃', name: 'night with stars', keywords: ['night', 'city'] },
      { char: '🌍', name: 'globe showing europe-africa', keywords: ['world', 'earth', 'globe'] },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    emojis: [
      { char: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bulb'] },
      { char: '📌', name: 'pushpin', keywords: ['pin', 'note'] },
      { char: '📎', name: 'paperclip', keywords: ['attach', 'clip'] },
      { char: '📝', name: 'memo', keywords: ['note', 'write'] },
      { char: '📋', name: 'clipboard', keywords: ['list', 'tasks'] },
      { char: '📁', name: 'file folder', keywords: ['folder', 'files'] },
      { char: '📂', name: 'open file folder', keywords: ['folder', 'files'] },
      { char: '🗂️', name: 'card index dividers', keywords: ['organize', 'files'] },
      { char: '📅', name: 'calendar', keywords: ['calendar', 'date'] },
      { char: '📆', name: 'tear-off calendar', keywords: ['calendar', 'date'] },
      { char: '📊', name: 'bar chart', keywords: ['chart', 'graph', 'stats'] },
      { char: '📈', name: 'chart increasing', keywords: ['growth', 'stats'] },
      { char: '📉', name: 'chart decreasing', keywords: ['decline', 'stats'] },
      { char: '💻', name: 'laptop', keywords: ['computer', 'laptop'] },
      { char: '🖥️', name: 'desktop computer', keywords: ['computer', 'monitor'] },
      { char: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type'] },
      { char: '🖱️', name: 'computer mouse', keywords: ['mouse'] },
      { char: '📱', name: 'mobile phone', keywords: ['phone', 'mobile'] },
      { char: '☎️', name: 'telephone', keywords: ['phone', 'call'] },
      { char: '🔋', name: 'battery', keywords: ['battery', 'power'] },
      { char: '🔌', name: 'electric plug', keywords: ['plug', 'power'] },
      { char: '💾', name: 'floppy disk', keywords: ['save', 'disk'] },
      { char: '💿', name: 'optical disk', keywords: ['cd', 'disk'] },
      { char: '🔍', name: 'magnifying glass', keywords: ['search', 'find', 'zoom'] },
      { char: '🔒', name: 'locked', keywords: ['lock', 'secure', 'private'] },
      { char: '🔓', name: 'unlocked', keywords: ['unlock', 'open'] },
      { char: '🔑', name: 'key', keywords: ['key', 'password'] },
      { char: '🔨', name: 'hammer', keywords: ['tool', 'build', 'fix'] },
      { char: '🛠️', name: 'hammer and wrench', keywords: ['tools', 'fix', 'settings'] },
      { char: '⚙️', name: 'gear', keywords: ['settings', 'config'] },
      { char: '🧰', name: 'toolbox', keywords: ['tools'] },
      { char: '🔗', name: 'link', keywords: ['link', 'chain', 'url'] },
      { char: '📦', name: 'package', keywords: ['box', 'delivery', 'package'] },
      { char: '💰', name: 'money bag', keywords: ['money', 'rich'] },
      { char: '💳', name: 'credit card', keywords: ['card', 'payment'] },
      { char: '🎁', name: 'wrapped gift', keywords: ['gift', 'present'] },
      { char: '🔔', name: 'bell', keywords: ['notification', 'alert'] },
      { char: '📢', name: 'loudspeaker', keywords: ['announce', 'megaphone'] },
      { char: '🧭', name: 'compass', keywords: ['compass', 'direction'] },
      { char: '⏰', name: 'alarm clock', keywords: ['clock', 'alarm', 'time'] },
      { char: '⏳', name: 'hourglass not done', keywords: ['time', 'wait'] },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emojis: [
      { char: '✅', name: 'check mark button', keywords: ['check', 'done', 'yes'] },
      { char: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'x'] },
      { char: '❗', name: 'exclamation mark', keywords: ['important', 'warning'] },
      { char: '❓', name: 'question mark', keywords: ['question', 'help'] },
      { char: '⚠️', name: 'warning', keywords: ['warning', 'caution', 'alert'] },
      { char: '🚫', name: 'prohibited', keywords: ['no', 'banned', 'forbidden'] },
      { char: '♻️', name: 'recycling symbol', keywords: ['recycle', 'green'] },
      { char: '💯', name: 'hundred points', keywords: ['100', 'perfect'] },
      { char: '✨', name: 'sparkles', keywords: ['sparkle', 'new', 'shiny'] },
      { char: '⭐', name: 'star', keywords: ['star', 'favorite'] },
      { char: '🌟', name: 'glowing star', keywords: ['star', 'shine'] },
      { char: '💫', name: 'dizzy', keywords: ['star', 'sparkle'] },
      { char: '🔴', name: 'red circle', keywords: ['red', 'circle', 'dot'] },
      { char: '🟠', name: 'orange circle', keywords: ['orange', 'circle'] },
      { char: '🟡', name: 'yellow circle', keywords: ['yellow', 'circle'] },
      { char: '🟢', name: 'green circle', keywords: ['green', 'circle'] },
      { char: '🔵', name: 'blue circle', keywords: ['blue', 'circle'] },
      { char: '🟣', name: 'purple circle', keywords: ['purple', 'circle'] },
      { char: '⚫', name: 'black circle', keywords: ['black', 'circle'] },
      { char: '⚪', name: 'white circle', keywords: ['white', 'circle'] },
      { char: '🔺', name: 'red triangle pointed up', keywords: ['triangle', 'warning'] },
      { char: '💠', name: 'diamond with a dot', keywords: ['diamond'] },
      { char: '🔶', name: 'large orange diamond', keywords: ['diamond'] },
      { char: '➕', name: 'plus', keywords: ['add', 'plus'] },
      { char: '➖', name: 'minus', keywords: ['subtract', 'minus'] },
      { char: '➗', name: 'divide', keywords: ['divide'] },
      { char: '✖️', name: 'multiply', keywords: ['multiply', 'times'] },
      { char: '♾️', name: 'infinity', keywords: ['infinite', 'infinity'] },
      { char: '💤', name: 'zzz', keywords: ['sleep', 'tired'] },
      { char: '💬', name: 'speech balloon', keywords: ['chat', 'comment', 'talk'] },
      { char: '💭', name: 'thought balloon', keywords: ['think', 'idea'] },
    ],
  },
]

/** Flat lookup used by search across all categories. */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis)
